import { chromium } from 'playwright';
const out = process.argv[2];
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const page = await browser.newPage({ viewport: { width: 1500, height: 940 }, deviceScaleFactor: 2 });
page.on('pageerror', e => console.log('PAGEERROR', e.message));
await page.goto(`file://${process.cwd()}/dist/index.html`);
await page.evaluate(() => localStorage.clear());
await page.reload();
await page.waitForTimeout(300);
await page.click('#tabs button:has-text("Command")');
await page.fill('#command-text', '3"\nSTD\nORIGIN 0 0 0\nE 2000\nN 600\nU 1500');
await page.click('[data-a="run-commands"]');
await page.waitForTimeout(400);
await page.keyboard.press('Escape'); await page.keyboard.press('f'); await page.waitForTimeout(200);
await page.click('#tabs button:has-text("Route")');
const cdp = await page.context().newCDPSession(page);
const pen = (type, x, y) => cdp.send('Input.dispatchMouseEvent', { type, x, y, button: type === 'mouseMoved' ? 'none' : 'left', buttons: type === 'mouseReleased' ? 0 : 1, clickCount: type === 'mouseMoved' ? 0 : 1, pointerType: 'pen', force: 0.5 });
const drawingNow = () => page.evaluate(() => JSON.parse(localStorage.getItem('iso-draw.drawing.v1')));
// 1. Drag a dimension figure with the pen.
const dim = await page.evaluate(() => { const r = document.querySelector('#canvas [data-dim]').getBoundingClientRect(); return { x: r.x + r.width / 2, y: r.y + r.height / 2, key: document.querySelector('#canvas [data-dim]').getAttribute('data-dim') }; });
const lineBefore = await page.evaluate(() => document.querySelector('#canvas .dim-line').getAttribute('y1'));
await pen('mousePressed', dim.x, dim.y); await page.waitForTimeout(60);
console.log('box opened on touch', await page.locator('.dim-editor').count(), 'hide key', await page.locator('.dim-keypad [data-extra]').innerText());
await pen('mouseMoved', dim.x + 20, dim.y + 30); await pen('mouseMoved', dim.x + 40, dim.y + 60); await page.waitForTimeout(60);
console.log('box gone as the drag starts', await page.locator('.dim-editor').count());
await pen('mouseReleased', dim.x + 40, dim.y + 60); await page.waitForTimeout(300);
const d1 = await drawingNow();
console.log('dim override', JSON.stringify(d1.dimOverrides), 'line y1', lineBefore, '->', await page.evaluate(() => document.querySelector('#canvas .dim-line').getAttribute('y1')));
await page.screenshot({ path: out + '/dim-moved.png', clip: { x: 200, y: 200, width: 1100, height: 600 } });
// Hide it via the keypad, then show again from the run panel.
const dim2 = await page.evaluate(() => { const r = document.querySelector('#canvas [data-dim]').getBoundingClientRect(); return { x: r.x + r.width / 2, y: r.y + r.height / 2 }; });
await pen('mousePressed', dim2.x, dim2.y); await page.waitForTimeout(60); await pen('mouseReleased', dim2.x, dim2.y); await page.waitForTimeout(100);
await page.locator('.dim-keypad [data-extra="0"]').dispatchEvent('pointerdown', { bubbles: true }); await page.waitForTimeout(300);
console.log('dims drawn after hide', await page.locator('#canvas .dim').count(), 'hidden keys', JSON.stringify(Object.entries((await drawingNow()).dimOverrides).filter(([, v]) => v.hidden).map(([k]) => k)));
await page.locator('#tab-body .run-list tbody tr').first().click(); await page.waitForTimeout(200);
await page.selectOption('#tab-body [data-f="nodim"]', 'show'); await page.waitForTimeout(300);
console.log('dims drawn after show', await page.locator('#canvas .dim').count());
await page.keyboard.press('Escape'); await page.waitForTimeout(150);
// 2. The N run between two elbows: fittings touch.
const weldsBefore = await page.evaluate(() => document.querySelectorAll('#canvas .weld .joint-bw').length);
await page.locator('#tab-body .run-list tbody tr').nth(1).click(); await page.waitForTimeout(200);
console.log('hud button', await page.locator('#hud-direct').innerText());
await page.click('#hud-direct'); await page.waitForTimeout(400);
const d2 = await drawingNow();
const runN = d2.runs[1];
const A = d2.nodes.find(n => n.id === runN.from).pos, B = d2.nodes.find(n => n.id === runN.to).pos;
console.log('direct', runN.direct, 'run length now', Math.round(Math.hypot(B.e - A.e, B.n - A.n, B.u - A.u)), 'welds marks', weldsBefore, '->', await page.evaluate(() => document.querySelectorAll('#canvas .weld .joint-bw').length));
await page.click('#tabs button:has-text("Welds")'); await page.waitForTimeout(200);
console.log('welds tab:', (await page.locator('#tab-body').innerText()).replace(/\n/g, ' | ').slice(0, 260));
await page.click('#tabs button:has-text("Items")'); await page.waitForTimeout(200);
console.log('items:', (await page.locator('#tab-body').innerText()).replace(/\n/g, ' | ').slice(0, 200));
await page.click('#tabs button:has-text("Route")'); await page.waitForTimeout(200);
await page.keyboard.press('f'); await page.waitForTimeout(200);
await page.screenshot({ path: out + '/direct.png', clip: { x: 200, y: 150, width: 1100, height: 700 } });
// 3. No weld here: tap a weld mark and choose it.
await page.keyboard.press('Escape'); await page.waitForTimeout(150);
const mark = await page.evaluate(() => { const r = document.querySelector('#canvas [data-weld]:not([data-weld-tag])').getBoundingClientRect(); return { x: r.x + r.width / 2, y: r.y + r.height / 2, key: document.querySelector('#canvas [data-weld]:not([data-weld-tag])').getAttribute('data-weld') }; });
const numbersBefore = await page.evaluate(() => [...document.querySelectorAll('#canvas .weld-no')].map(t => t.textContent).join(' '));
await pen('mousePressed', mark.x, mark.y); await page.waitForTimeout(60); await pen('mouseReleased', mark.x, mark.y); await page.waitForTimeout(100);
console.log('weld box', await page.locator('.dim-editor').count(), 'extra', await page.locator('.dim-keypad [data-extra]').innerText());
await page.locator('.dim-keypad [data-extra="0"]').dispatchEvent('pointerdown', { bubbles: true }); await page.waitForTimeout(300);
console.log('numbers', numbersBefore, '->', await page.evaluate(() => [...document.querySelectorAll('#canvas .weld-no')].map(t => t.textContent).join(' ')), 'hollow marks', await page.locator('#canvas .weld.no-weld').count());
await page.click('#tabs button:has-text("Welds")'); await page.waitForTimeout(200);
console.log('not welded section', await page.locator('[data-restore-weld]').count(), 'total line', (await page.locator('#tab-body').innerText()).match(/Total \d+/)?.[0]);
await page.click('[data-restore-weld]'); await page.waitForTimeout(300);
console.log('after restore: hollow', await page.locator('#canvas .weld.no-weld').count(), 'total', (await page.locator('#tab-body').innerText()).match(/Total \d+/)?.[0]);
await browser.close();
