/**
 * Turns the built page into an installable app.
 *
 * Writes the icons, the manifest and a service worker into dist/, and links
 * them from the built page. The service worker caches the whole app on first
 * run, so once installed it opens and draws with no network at all — which is
 * the point on a site or a workshop floor.
 *
 *   npm run app   ->  dist/ ready to install
 */
import { readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';

const NAME = 'Isometric Piping';
const SHORT = 'Isometrics';

/** The app mark: three isometric axes meeting at a point. */
function iconSvg(size, bg, fg) {
  const c = size / 2;
  const r = size * 0.3;
  const leg = (dx, dy) =>
    `<line x1="${c}" y1="${c}" x2="${(c + dx * r).toFixed(1)}" y2="${(c + dy * r).toFixed(1)}"/>`;
  const k = Math.cos(Math.PI / 6);
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${size} ${size}" width="${size}" height="${size}">
  <rect width="${size}" height="${size}" rx="${(size * 0.22).toFixed(1)}" fill="${bg}"/>
  <g stroke="${fg}" stroke-width="${(size * 0.07).toFixed(1)}" stroke-linecap="round" fill="none">
    ${leg(k, 0.5)}${leg(-k, 0.5)}${leg(0, -1)}
  </g>
  <circle cx="${c}" cy="${c}" r="${(size * 0.075).toFixed(1)}" fill="${fg}"/>
</svg>`;
}

await writeFile('dist/icon.svg', iconSvg(512, '#1a212c', '#6fb2ff'));
await writeFile('dist/icon-maskable.svg', iconSvg(512, '#1a212c', '#6fb2ff'));

const manifest = {
  name: NAME,
  short_name: SHORT,
  description: 'Draw piping isometrics and print them as a fabrication sheet.',
  start_url: './index.html',
  scope: './',
  display: 'standalone',
  orientation: 'any',
  background_color: '#eef1f6',
  theme_color: '#1a212c',
  icons: [
    { src: './icon.svg', sizes: 'any', type: 'image/svg+xml', purpose: 'any' },
    { src: './icon-maskable.svg', sizes: 'any', type: 'image/svg+xml', purpose: 'maskable' },
  ],
};
await writeFile('dist/manifest.webmanifest', JSON.stringify(manifest, null, 2));

// The cache name carries a hash of the page, so a rebuild replaces the old copy
// instead of serving it forever.
const page = await readFile('dist/index.html', 'utf8');
const version = createHash('sha256').update(page).digest('hex').slice(0, 12);

const sw = `/* Generated by scripts/pwa.mjs — do not edit. */
const CACHE = 'iso-draw-${version}';
const ASSETS = ['./', './index.html', './manifest.webmanifest', './icon.svg', './icon-maskable.svg'];

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

// Cache first: the app is one file and never needs the network to draw.
self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET' || new URL(request.url).origin !== self.location.origin) return;
  event.respondWith(
    caches.match(request, { ignoreSearch: true }).then(
      (hit) =>
        hit ||
        fetch(request)
          .then((response) => {
            if (response.ok) {
              const copy = response.clone();
              caches.open(CACHE).then((c) => c.put(request, copy));
            }
            return response;
          })
          .catch(() => caches.match('./index.html')),
    ),
  );
});
`;
await writeFile('dist/sw.js', sw);

// Link the manifest and register the worker.
const head = `<link rel="manifest" href="./manifest.webmanifest">
    <link rel="icon" type="image/svg+xml" href="./icon.svg">
    <meta name="theme-color" content="#1a212c">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <meta name="apple-mobile-web-app-title" content="${SHORT}">`;
const register = `<script>
      if ('serviceWorker' in navigator) {
        addEventListener('load', () => navigator.serviceWorker.register('./sw.js').catch(() => {}));
      }
    </script>`;

if (page.includes('manifest.webmanifest')) {
  throw new Error('dist/index.html already carries the app tags — run `npm run build` first.');
}

// The bundled JavaScript builds a whole document in a string for printing, so
// it contains </head> and </body> of its own. The real ones are the last.
function insertBefore(html, closing, block) {
  const at = html.lastIndexOf(closing);
  if (at < 0) throw new Error(`could not find ${closing} to add the app tags before`);
  return `${html.slice(0, at)}    ${block}\n  ${html.slice(at)}`;
}

const withTags = insertBefore(insertBefore(page, '</head>', head), '</body>', register);
await writeFile('dist/index.html', withTags);

// A broken injection would only show up as a blank page, so check the shape.
if (!/<\/head>[\s\S]*<body/i.test(withTags) || withTags.split('<body').length !== page.split('<body').length) {
  throw new Error('the app tags landed in the wrong place');
}

console.log(`dist/ is installable  (cache iso-draw-${version})`);
